# This is a basic workflow to help you get started with Actions

name: Deployed to Firebase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firebase-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # Sets up nodejs for vue compiling
      - uses: actions/setup-node@master
      
      # Installs the project dependices
      - run: npm install
      
      # Builds the project to the distro folder
      - run: npm run build
        
      # Loads the firebase action repository
      - uses: w9jds/firebase-action@master
        
        # Sets up firebase hosting deployment
        with:
           args: deploy --only hosting
           
       # Creates a refrence to the firebase project to deploy to
        env:  
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  
      
      
